---

- hosts: all
  become: true
  pre_tasks:

  - name: installing dnf and epel-release
    yum:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update Upgrade for CentOS Node
    dnf:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Dpkg configure for Ubuntu
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Upgrade Update for Ubuntu Node
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - ubuntu

- hosts: centos
  become: true
  roles:
    - centos
